### ISSUE TITLE
Design Logo

### ISSUE THREAD

**Issue by Sabo2k** [ivandukov/TreasureTrove#14]
It would be good to have a fitting logo for our Web App. 

Here are some interesting articles:
- https://www.wix.com/blog/logo-psychology
- https://www.wix.com/blog/logo-colors

**Comment by ivandukov** [comment]
We can some image generation AI? Opinion?

**Comment by Sabo2k** [comment]
Here is a fitting icon for our logo

<img 
   src="https://github.com/ivandukov/TreasureTrove/assets/63151233/af805e56-3449-4e7d-8159-ee6793fb25e0" 
   width="250"
/>

**Comment by Sabo2k** [comment]
![Bild1](https://github.com/user-attachments/assets/609a945a-3750-4873-ac12-6b3373fdad3b)
